---
- name: My Test Playbook
  hosts: webservers
  become: yes
  tasks:
  - name: Installing Httpd Service
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Starting Httpd Service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: Installing Apache2 Service
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Starting Apache2 Service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: Coping a File
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
